name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: '24.x'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      
      - name: Install Node Dependencies
        run: npm install
      
      - name: Install templ
        shell: bash
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Template Generate
        run: templ generate ./...

      - name: Install Go Dependencies
        run: go mod tidy && go mod vendor

      - name: CSS Generate
        shell: bash
        run: npx @tailwindcss/cli -c tailwind.config.js -i ./web/static/tailwind.css -o ./web/static/app.css --minify

      - name: Generate test coverage
        run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out
      
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: coverage.out
          report: true
          chart: true
          amend: true
        if: |
          matrix.os == 'ubuntu-latest' &&
          github.event_name == 'push'  
        continue-on-error: true
